### ISSUE TITLE
[REFACTOR] 애플 로그인 추가 시 관련사항

### ISSUE THREAD

**Issue by ryuwon-dev** [9oormthon-univ/2024_DANPOONG_TEAM_42_BE#14]
## 📢 노트

애플 로그인을 장착하는 과정에서 Retry 편의성때문에 우선 OpenFeign 달아뒀는데
OpenFeign에는 스프링 클라우드가 필요합니다 그래서 장착하려고 보는 순간..
저희가 스프링 버전을 3.3.5v 을 사용하다보니 아직 스프링 클라우드가 해당 버전까지는 지원하지 않더라구요 ㅜ

그래서 우선 코드를 작성하면서 스프링 v3.2.11 으로 설정해둔 상황인데
버전 다운그레이드를 유지 할까요..? 아니면 원래대로 되돌리고 RestClient로 진행할까여?

현재 애플로그인은 정상적으로 작동합니다..!

**Comment by kduoh99** [comment]
확인했습니다, OpenFeign 의존성과 더불어 버전 제약이 있나보네요..!

저희 프로젝트에서 구현된 카카오 로그인 로직과의 일관성, 스프링 최신 버전에서 기본 지원 + 코드 가독 면을 고려해봤을 때 RestClient로 진행하는게 적절하다 생각합니다!

**Comment by ryuwon-dev** [comment]
네 RestClient로 수정하였습니다!

> #20
